'------------------------------------------------------------------------------
' <auto-generated>
'     이 코드는 도구를 사용하여 생성되었습니다.
'     런타임 버전:4.0.30319.42000
'
'     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
'     이러한 변경 내용이 손실됩니다.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    '이 클래스는 ResGen 또는 Visual Studio와 같은 도구를 통해 StronglyTypedResourceBuilder
    '클래스에서 자동으로 생성되었습니다.
    '멤버를 추가하거나 제거하려면 .ResX 파일을 편집한 다음 /str 옵션을 사용하여 ResGen을
    '다시 실행하거나 VS 프로젝트를 다시 빌드하십시오.
    '''<summary>
    '''  지역화된 문자열 등을 찾기 위한 강력한 형식의 리소스 클래스입니다.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  이 클래스에서 사용하는 캐시된 ResourceManager 인스턴스를 반환합니다.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("AlcUpdate.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  이 강력한 형식의 리소스 클래스를 사용하여 모든 리소스 조회에 대해 현재 스레드의 CurrentUICulture 속성을
        '''  재정의합니다.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        '''</summary>
        Friend ReadOnly Property _0_50() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("0-50", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        '''</summary>
        Friend ReadOnly Property _0_Filled_50() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("0 Filled-50", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        '''</summary>
        Friend ReadOnly Property _1_50() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("1-50", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        '''</summary>
        Friend ReadOnly Property _1_501() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("1-501", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        '''</summary>
        Friend ReadOnly Property _1_Filled_50() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("1 Filled-50", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        '''</summary>
        Friend ReadOnly Property _10_50() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("10-50", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        '''</summary>
        Friend ReadOnly Property _10_Filled_50() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("10 Filled-50", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        '''</summary>
        Friend ReadOnly Property _11_50() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("11-50", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        '''</summary>
        Friend ReadOnly Property _11_Filled_50() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("11 Filled-50", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        '''</summary>
        Friend ReadOnly Property _12_50() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("12-50", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        '''</summary>
        Friend ReadOnly Property _12_Filled_50() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("12 Filled-50", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        '''</summary>
        Friend ReadOnly Property _13_50() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("13-50", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        '''</summary>
        Friend ReadOnly Property _13_Filled_50() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("13 Filled-50", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        '''</summary>
        Friend ReadOnly Property _14_50() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("14-50", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        '''</summary>
        Friend ReadOnly Property _14_Filled_50() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("14 Filled-50", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        '''</summary>
        Friend ReadOnly Property _15_50() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("15-50", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        '''</summary>
        Friend ReadOnly Property _15_Filled_50() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("15 Filled-50", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        '''</summary>
        Friend ReadOnly Property _2_50() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("2-50", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        '''</summary>
        Friend ReadOnly Property _2_Filled_50() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("2 Filled-50", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        '''</summary>
        Friend ReadOnly Property _3_50() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("3-50", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        '''</summary>
        Friend ReadOnly Property _3_Filled_50() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("3 Filled-50", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        '''</summary>
        Friend ReadOnly Property _4_50() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("4-50", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        '''</summary>
        Friend ReadOnly Property _4_Filled_50() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("4 Filled-50", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        '''</summary>
        Friend ReadOnly Property _5_50() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("5-50", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        '''</summary>
        Friend ReadOnly Property _5_Filled_50() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("5 Filled-50", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        '''</summary>
        Friend ReadOnly Property _6_50() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("6-50", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        '''</summary>
        Friend ReadOnly Property _6_Filled_50() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("6 Filled-50", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        '''</summary>
        Friend ReadOnly Property _7_50() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("7-50", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        '''</summary>
        Friend ReadOnly Property _7_Filled_50() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("7 Filled-50", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        '''</summary>
        Friend ReadOnly Property _8_50() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("8-50", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        '''</summary>
        Friend ReadOnly Property _8_Filled_50() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("8 Filled-50", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        '''</summary>
        Friend ReadOnly Property _9_50() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("9-50", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        '''</summary>
        Friend ReadOnly Property _9_Filled_50() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("9 Filled-50", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        '''</summary>
        Friend ReadOnly Property _Exit() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Exit", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        '''</summary>
        Friend ReadOnly Property Add() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Add", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        '''</summary>
        Friend ReadOnly Property Add_Folder_100() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Add Folder-100", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        '''</summary>
        Friend ReadOnly Property Add_Folder_1001() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Add Folder-1001", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        '''</summary>
        Friend ReadOnly Property Add_Folder_Filled_100() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Add Folder Filled-100", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        '''</summary>
        Friend ReadOnly Property C0() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("C0", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        '''</summary>
        Friend ReadOnly Property C0_F() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("C0_F", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        '''</summary>
        Friend ReadOnly Property C0_F1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("C0_F1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        '''</summary>
        Friend ReadOnly Property C01() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("C01", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        '''</summary>
        Friend ReadOnly Property C1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("C1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        '''</summary>
        Friend ReadOnly Property C1_F() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("C1_F", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        '''</summary>
        Friend ReadOnly Property C2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("C2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        '''</summary>
        Friend ReadOnly Property C2_F() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("C2_F", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        '''</summary>
        Friend ReadOnly Property C3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("C3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        '''</summary>
        Friend ReadOnly Property C3_F() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("C3_F", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        '''</summary>
        Friend ReadOnly Property C4() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("C4", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        '''</summary>
        Friend ReadOnly Property C4_F() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("C4_F", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        '''</summary>
        Friend ReadOnly Property C5() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("C5", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        '''</summary>
        Friend ReadOnly Property C5_F() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("C5_F", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        '''</summary>
        Friend ReadOnly Property C6() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("C6", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        '''</summary>
        Friend ReadOnly Property C6_F() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("C6_F", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        '''</summary>
        Friend ReadOnly Property C7() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("C7", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        '''</summary>
        Friend ReadOnly Property C7_F() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("C7_F", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        '''</summary>
        Friend ReadOnly Property CLS_50() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("CLS-50", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        '''</summary>
        Friend ReadOnly Property CLS_Filled_50() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("CLS Filled-50", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        '''</summary>
        Friend ReadOnly Property Delete() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Delete", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        '''</summary>
        Friend ReadOnly Property Delete_100() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Delete-100", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        '''</summary>
        Friend ReadOnly Property Delete_Filled_100() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Delete Filled-100", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        '''</summary>
        Friend ReadOnly Property DSC() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("DSC", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        '''</summary>
        Friend ReadOnly Property DSC2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("DSC2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        '''</summary>
        Friend ReadOnly Property Edit() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Edit", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        '''</summary>
        Friend ReadOnly Property Edit_F() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Edit_F", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        '''</summary>
        Friend ReadOnly Property Edit1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Edit1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        '''</summary>
        Friend ReadOnly Property Enter_Key_50() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Enter Key-50", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        '''</summary>
        Friend ReadOnly Property Enter_Key_Filled_50() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Enter Key Filled-50", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        '''</summary>
        Friend ReadOnly Property excel() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("excel", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        '''</summary>
        Friend ReadOnly Property excel_f() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("excel_f", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        '''</summary>
        Friend ReadOnly Property Exit_f() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Exit_f", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        '''</summary>
        Friend ReadOnly Property FTEch() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("FTEch", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        '''</summary>
        Friend ReadOnly Property green() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("green", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        '''</summary>
        Friend ReadOnly Property grey() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("grey", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        '''</summary>
        Friend ReadOnly Property human() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("human", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        '''</summary>
        Friend ReadOnly Property human_f() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("human_f", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        '''</summary>
        Friend ReadOnly Property Keyboard() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Keyboard", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        '''</summary>
        Friend ReadOnly Property Keyboard_f() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Keyboard_f", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        '''</summary>
        Friend ReadOnly Property Microsoft_Excel_100() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Microsoft Excel-100", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        '''</summary>
        Friend ReadOnly Property Microsoft_Excel_1001() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Microsoft Excel-1001", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        '''</summary>
        Friend ReadOnly Property PART() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("PART", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        '''</summary>
        Friend ReadOnly Property PART1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("PART1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        '''</summary>
        Friend ReadOnly Property printer() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("printer", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        '''</summary>
        Friend ReadOnly Property ptinter_f() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ptinter_f", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        '''</summary>
        Friend ReadOnly Property red() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("red", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        '''</summary>
        Friend ReadOnly Property save() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("save", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        '''</summary>
        Friend ReadOnly Property save_f() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("save_f", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        '''</summary>
        Friend ReadOnly Property save1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("save1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        '''</summary>
        Friend ReadOnly Property save2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("save2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        '''</summary>
        Friend ReadOnly Property scanner() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("scanner", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        '''</summary>
        Friend ReadOnly Property scanner_F() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("scanner_F", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        '''</summary>
        Friend ReadOnly Property screenshot1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("screenshot1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        '''</summary>
        Friend ReadOnly Property search() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("search", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        '''</summary>
        Friend ReadOnly Property search_f() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("search_f", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        '''</summary>
        Friend ReadOnly Property search05() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("search05", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        '''</summary>
        Friend ReadOnly Property search1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("search1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        '''</summary>
        Friend ReadOnly Property search2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("search2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        '''</summary>
        Friend ReadOnly Property serial() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("serial", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        '''</summary>
        Friend ReadOnly Property serial_f() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("serial_f", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        '''</summary>
        Friend ReadOnly Property setting() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("setting", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        '''</summary>
        Friend ReadOnly Property setting_f() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("setting_f", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        '''</summary>
        Friend ReadOnly Property shutdown() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("shutdown", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        '''</summary>
        Friend ReadOnly Property shutdown_f() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("shutdown_f", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        '''</summary>
        Friend ReadOnly Property shutdown1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("shutdown1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        '''</summary>
        Friend ReadOnly Property TEST() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TEST", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        '''</summary>
        Friend ReadOnly Property Toggle_Off() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Toggle Off", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        '''</summary>
        Friend ReadOnly Property Toggle_On() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Toggle On", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        '''</summary>
        Friend ReadOnly Property tool() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("tool", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        '''</summary>
        Friend ReadOnly Property Tool_f() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Tool_f", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
